export const EDGE_VOCAB = {
  attacks: {
    id: "attacks",
    label: "Attacks",
    description: "The subject attacks the object.",
    kind: "combat",
    subjectType: "actor",
    objectType: "actor",
  },
  affects: {
    id: "affects",
    label: "Affects",
    description: "The subject applies or influences a condition on the object.",
    kind: "status",
    subjectType: "actor",
    objectType: "actor",
  },
  has: {
    id: "has",
    label: "Has",
    description: "The subject possesses or contains the object.",
    kind: "ownership",
    subjectType: "actor",
    objectType: "object",
  },
  equips: {
    id: "equips",
    label: "Equips",
    description: "The subject equips the object.",
    kind: "equipment",
    subjectType: "actor",
    objectType: "object",
  },
  uses: {
    id: "uses",
    label: "Uses",
    description: "The subject uses the object, item, or skill.",
    kind: "interaction",
    subjectType: "actor",
    objectType: "capability",
  },
  targets: {
    id: "targets",
    label: "Targets",
    description: "The subject selects the object as its target.",
    kind: "intent",
    subjectType: "actor",
    objectType: "actor",
  },
  grants: {
    id: "grants",
    label: "Grants",
    description: "The subject grants the object an ability, property, or status.",
    kind: "grant",
    subjectType: "object",
    objectType: "actor",
  },
};
