export const STATE_KEY_VOCAB = {
  hp: {
    id: "hp",
    label: "HP",
    description: "State key for health points.",
    category: "stat",
    statId: "hp",
    default: 10,
  },
  atk: {
    id: "atk",
    label: "ATK",
    description: "State key for attack.",
    category: "stat",
    statId: "atk",
    default: 1,
  },
  def: {
    id: "def",
    label: "DEF",
    description: "State key for defense.",
    category: "stat",
    statId: "def",
    default: 1,
  },
  int: {
    id: "int",
    label: "INT",
    description: "State key for intelligence.",
    category: "stat",
    statId: "int",
    default: 1,
  },
  res: {
    id: "res",
    label: "RES",
    description: "State key for resistance.",
    category: "stat",
    statId: "res",
    default: 1,
  },
  spd: {
    id: "spd",
    label: "SPD",
    description: "State key for speed.",
    category: "stat",
    statId: "spd",
    default: 1,
  },
};
