export const WORLD_RELATION_CONTRACTS = {
  attacks: {
    id: "attacks",
    label: "Attacks Contract",
    description: "Attack interactions can damage and optionally apply harmful statuses.",
    sourceTypes: ["role", "hero", "enemy"],
    targetTypes: ["role", "hero", "enemy"],
    allowedOpTypes: ["numericEffect.state", "graft.state"],
    allowedStatKeys: ["hp"],
    allowedStateKeys: ["debuffs", "statuses"],
    supportsSecondaryEffects: true,
    effectMode: "primary-with-secondary",
    notes:
      "Use Calculation for HP damage math. Use Apply Condition for secondary effects like poison, stun, confuse, or freeze.",
  },
  heals: {
    id: "heals",
    label: "Heals Contract",
    description: "Heal interactions increase hp only.",
    sourceTypes: ["role", "hero", "npc"],
    targetTypes: ["role", "hero", "npc"],
    allowedOpTypes: ["numericEffect.state"],
    allowedStatKeys: ["hp"],
    allowedStateKeys: [],
    supportsSecondaryEffects: false,
    effectMode: "primary-only",
    notes:
      "Use Calculation for HP healing math with base amount, derivation, and minimum floor.",
  },
  buffs: {
    id: "buffs",
    label: "Buffs Contract",
    description: "Buff interactions add beneficial state entries.",
    sourceTypes: ["role", "hero", "npc"],
    targetTypes: ["role", "hero", "npc"],
    allowedOpTypes: ["graft.state"],
    allowedStatKeys: [],
    allowedStateKeys: ["buffs"],
    supportsSecondaryEffects: false,
    effectMode: "state-lane",
    notes: "Use Apply Condition to add helpful effects like shield or regen.",
  },
  debuffs: {
    id: "debuffs",
    label: "Debuffs Contract",
    description: "Debuff interactions add harmful state entries.",
    sourceTypes: ["role", "hero", "enemy", "npc"],
    targetTypes: ["role", "hero", "enemy", "npc"],
    allowedOpTypes: ["graft.state"],
    allowedStatKeys: [],
    allowedStateKeys: ["debuffs"],
    supportsSecondaryEffects: false,
    effectMode: "state-lane",
    notes: "Use Apply Condition to add harmful effects like poison, stun, confuse, or freeze.",
  },
};
